<a href="https://colab.research.google.com/github/the-ocean-git/2020-2-AI/blob/master/code/01_tf_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [ ]:
a=tf.constant(5)
b=tf.constant(3)
print(a+b)

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
c=tf.constant('hello, world!')
print(c)
print(c.numpy())

tf.Tensor(b'hello, world!', shape=(), dtype=string)
b'hello, world!'


In [ ]:
a=tf.constant(3)
a
a.shape

TensorShape([])

In [ ]:
a.dtype

tf.int32

In [ ]:
a.numpy()

3

In [ ]:
b=tf.constant(3.)
b

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
b.shape

TensorShape([])

In [ ]:
b.dtype

tf.float32

In [ ]:
b.numpy()

3.0

In [ ]:
a = tf.constant([1, 2, 3])
a.shape 

TensorShape([3])

In [ ]:
a = tf.constant([[1,2,3],[4,5,6]])
a.shape

TensorShape([2, 3])

In [ ]:
a = tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a.shape

TensorShape([2, 2, 3])

In [ ]:
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
x=tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool, lambda: tf.add(x, 1.), lambda: tf.add(x, 10.))

print(res)
print(res.numpy())

tf.Tensor(2.0, shape=(), dtype=float32)
2.0


In [ ]:
x=tf.constant(2)
y=tf.constant(5)
def f1(): return tf.multiply(x, 17)
def f2(): return tf.add(y, 23)
r= tf.cond(tf.less(x,y), f1, f2)

r.numpy()

34

In [ ]:
#1차원 배열 텐서
t = tf.constant([1,2,3])
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
x=tf.constant([1,2,3])
y=tf.constant([5,6,7])

print((x+y).numpy())

[ 6  8 10]


In [ ]:
a=tf.constant([5], dtype=tf.float32)
b=tf.constant([10], dtype=tf.float32)
c=tf.constant([2], dtype=tf.float32)
print(a.numpy())

d = a * b + c

print(d)
print(d.numpy())

[5.]
tf.Tensor([52.], shape=(1,), dtype=float32)
[52.]


In [ ]:
x=tf.constant([[0],[10],[20],[30]])
y=tf.constant([0,1,2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
import numpy as np

print(np.arange(3))
print(np.ones((3,3)))
print()

x=tf.constant((np.arange(3)))
y=tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [ ]:
x=tf.constant((np.arange(3)))
y=tf.constant([5],dtype=tf.int64)
print((x+y).numpy())

x=tf.constant((np.ones((3,3)))
y=tf.constant(np.arange(3), dtype=tf.double)

print((x+y).numpy())

x=tf.constant(np.arange(3).reshape(3,1))
y=tf.constant(np.arange(3))
print((x+y),numpy())

SyntaxError: ignored

In [ ]:
a=2
b=3
c=tf.add(a,b)
print(c.numpy())

5


In [ ]:
x=2
y=3
add_op = tf.add(x,y)
mul_op = tf.multiply(x,y)
pow_op = tf.pow(add_op, mul_op)

print(pow_op.numpy())

15625


In [ ]:
a=tf.constant(2.)
b=tf.constant(3.)
c=tf.constant(5.)

#Some more operations.
mean = tf.reduce_mean([a,b,c])
sum = tf.reduce_sum([a,b,c])

print("mean = ", mean.numpy())
print("sum =", sum.numpy())

mean =  3.3333333
sum = 10.0


In [ ]:
#Matrix multipllications 1
matrix1 = tf.constant([[1.,2.],[3.,4.]])
matrix2 = tf.constant([[2.,0.],[1.,2.]])

gop = tf.matmul(matrix1, matrix2)
print(gop.numpy())

#Matrix multipllications 2
gop = tf.matmul(matrix2, matrix1)
print(gop.numpy())

[[ 4.  4.]
 [10.  8.]]
[[ 2.  4.]
 [ 7. 10.]]
